### PR TITLE
Major Rewrite

### LINKED ISSUE #30: d!code changes pls fix
basically, to make it more user-friendly, please make `d!code` as epic as described below:

- `d!code get <user>` (to prevent having issues later on, I don't trust JavaScript at all)
- `d!code set <code>`
- `d!code remove`

thankies

### LINKED ISSUE #31: Convert to Commando
Currently we take commands very literally through parsing. It would be nice to use a library such as the officially recommended [Commando](https://discord.js.org/#/docs/commando/master/general/welcome).

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
This will introduce a lot of new / fixed stuff:
- Rewrite of almost all modules. This would close #30.
- Using redis instead of JSON, regarding #23.
- Adding discord.js-Commando. This would close #31.

*Don't squish / merge this yet, thanks.*

### CODE REVIEW

**Comment by WiiNoMa** [comment]
now this, this is perfection by the apple man himself

**Comment by Artuto** [comment]
Ayyy lmao redis

**Comment by Apfel** [comment]
Okay I tried to fix it for 5 minutes now and no I don't get it working because JS feels like cancer imo

so fuck it thanks

**Comment by Artuto** [comment]
LMFAO

**Comment by spotlightishere** [comment]
Instead of giving up, what's the issue? How can we all continue/fix your PR? It looks to have enormous help.

**Comment by Apfel** [comment]
Basically, I would work on this more if it wouldn't be written in JavaScript, since I seem to have problems with it.

Not only is npm pretty bad, the language itself isn't my thing at all.

**Comment by Apfel** [comment]
However, I would really appreciate help from other developers that do have more experience with JavaScript, **[discord.js](https://github.com/discordjs/discord.js/)**, **[discord.js-commando](https://github.com/discordjs/Commando)**, **[node_redis](https://github.com/NodeRedis/node_redis)** and **[other modules](https://github.com/Apfel/Disconnect24-bot/blob/master/package.json#L17)** related to my fork.

**Comment by iDroid27** [comment]
>>redis
https://comps.canstockphoto.com/man-having-a-heart-attack-bending-stock-photo_csp3673542.jpg

**Comment by yeah-its-gloria** [comment]
Closed because nobody cares ~~check out my Go fork~~

**Pull request closed without merging**
